version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mayura-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://api-gateway:8000
      - REACT_APP_VERSION=1.0.0
      - REACT_APP_OFFLINE_STORAGE_KEY=mayurapos-data
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - mayura-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  # Use the same network as the backend services
  mayura-network:
    external: true